### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by lewiseason** [lewiseason/yavm#5]
When certain actions are performed, optionally shell out and do something else.

The config for this may look something like this:

```yaml
---
:major: 5
# ...
hooks:
  - when: "inc major"
    do: "rm -r test/aruba"
```
